import Footer from "@/components/footer";
import Header from "@/components/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <script src="https://cdn.tailwindcss.com"></script>
      </body>
    </html>
  );
}
